version: 1.0.0
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    restart: always
    container_name: quiz-client-prod
    image: quiz-client-prod
    ports:
      - 3000:3000
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    restart: always
    container_name: quiz-server-prod
    image: quiz-server-prod
    ports:
      - 4000:4000
    volumes:
      - ./server:/app/server
      - /app/server/node_modules
